name: MakeMeAdmin
author: Xenophilicy
version: 1.6.0
description: Quickly switch your PurePerms group with a UI
main: Xenophilicy\MakeMeAdmin\MakeMeAdmin
api: 3.0.0
depend:
- PurePerms
commands:
  makemeadmin:
    permission: makemeadmin.info
    description: Get info on MakeMeAdmin
permissions:
  makemeadmin.info:
    default: op