name: MakeMeAdmin
author: Xenophilicy
version: 1.6.0
description: Quickly switch your group from PurePerms, inside a simple UI.
main: Xenophilicy\MakeMeAdmin\MakeMeAdmin
api: 3.0.0
depend:
- PurePerms
commands:
  mma:
    description: Quickly change your rank!
