name: MakeMeAdmin
author: Xenophilicy
version: 1.5.2
description: Quickly switch your group from PurePerms, inside a simple UI.
main: Xenophilicy\MakeMeAdmin\MakeMeAdmin
api: 3.0.0
depend:
- PurePerms
commands:
  mma:
    description: Quickly change your rank!
    permission: makemeadmin.use.ui
permissions:
  makemeadmin.use.ui:
    default: op
    description: Allows use of all MakeMeAdmin permissions
